/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Student_Login;
import Home.Home;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Prudhwi Raj Krishna
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Science = new javax.swing.JTextField();
        maths = new javax.swing.JTextField();
        ss = new javax.swing.JTextField();
        eng = new javax.swing.JTextField();
        sl = new javax.swing.JTextField();
        Result = new javax.swing.JLabel();
        Grade = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        desc = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(238, 250, 222));
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Result");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Student ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 160, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 100, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 110, -1));

        Science.setEditable(false);
        Science.setBackground(new java.awt.Color(238, 250, 222));
        Science.setBorder(null);
        jPanel1.add(Science, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 370, -1));

        maths.setEditable(false);
        maths.setBackground(new java.awt.Color(238, 250, 222));
        maths.setBorder(null);
        jPanel1.add(maths, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 370, -1));

        ss.setEditable(false);
        ss.setBackground(new java.awt.Color(238, 250, 222));
        ss.setBorder(null);
        jPanel1.add(ss, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 370, -1));

        eng.setEditable(false);
        eng.setBackground(new java.awt.Color(238, 250, 222));
        eng.setBorder(null);
        jPanel1.add(eng, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 370, -1));

        sl.setEditable(false);
        sl.setBackground(new java.awt.Color(238, 250, 222));
        sl.setBorder(null);
        jPanel1.add(sl, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 370, -1));

        Result.setBackground(new java.awt.Color(0, 0, 0));
        Result.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Result.setText("  ");
        jPanel1.add(Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 110, 20));

        Grade.setBackground(new java.awt.Color(0, 0, 0));
        Grade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Grade.setText("  ");
        jPanel1.add(Grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 110, 20));

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 0, 204));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("Logout");
        logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 140, 30));

        Home.setBackground(new java.awt.Color(0, 0, 0));
        Home.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(0, 0, 204));
        Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home.setText("Home");
        Home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, 30));

        name.setBackground(new java.awt.Color(0, 0, 0));
        name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        name.setText("  ");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 400, 30));

        desc.setEditable(false);
        desc.setBackground(new java.awt.Color(238, 250, 222));
        desc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        desc.setBorder(null);
        jPanel1.add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 330, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        jPanel2.setBackground(new java.awt.Color(223, 223, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 254, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        Home Main = new Home();
        Main.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_HomeMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login login = new Login();
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_logoutMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        resetText();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        display();

    }//GEN-LAST:event_jButton1MouseClicked
    public void resetText() {
        id.setText("");
        maths.setText("");
        name.setText("");
        eng.setText("");
        desc.setText("");
        sl.setText("");
        ss.setText("");
        Science.setText("");
        Grade.setText("");
        Result.setText("");
    }    public void display() {
        try {
            if (id.getText().isBlank() == false || id.getText().isEmpty() == false) {

                Connection con = Login.connection();
                int ID = Integer.parseInt(id.getText());
                if (id.getText().startsWith("15400") && id.getText().length() == 6) {
                    String sql = "SELECT * FROM STUDENT where ID=" + ID;
                    PreparedStatement prest = con.prepareStatement(sql);
                    ResultSet rs = prest.executeQuery();

                    while (rs.next()) {

                        String num[] = rs.getString("Marksof5").split(",");
                        name.setText("Academic Result Of "+rs.getString("Username"));
                        desc.setText("  Subjects\t\t\t Marks");
                        Science.setText("Science \t\t\t  "+num[0]);
                        maths.setText("Mathematics \t\t\t  "+ num[1]);
                        ss.setText("Social Science \t\t\t  "+num[2]);
                        eng.setText("English        \t\t\t  "+num[3]);
                        sl.setText("Second Language\t\t  "+num[4]);
                        Grade.setText("Grade  : "+rs.getString("Grade"));
                        if (rs.getString("Grade").equals("F")) {
                            Result.setText("Result :\t\t\t Failed");
                        } else {
                            Result.setText("Result  :\t\t\t Pass");
                        }
                    }

                } else {
                    JOptionPane.showConfirmDialog(rootPane, "Invalid ID", "Error", 2);
                }
            }
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showConfirmDialog(rootPane, "Wrong or Invalid Student ID", "Error", 2);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Grade;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Result;
    private javax.swing.JTextField Science;
    private javax.swing.JTextField desc;
    private javax.swing.JTextField eng;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logout;
    private javax.swing.JTextField maths;
    private javax.swing.JLabel name;
    private javax.swing.JTextField sl;
    private javax.swing.JTextField ss;
    // End of variables declaration//GEN-END:variables
}
